[package]
name = "eventity_macro"
version = "0.1.0"
edition = "2024"
description = "Derive macros for the Eventity request and event library"
license = "MIT"
repository = "https://github.com/navlas08/eventity"
keywords = ["events", "derive", "proc-macro"]
categories = ["asynchronous", "development-tools::procedural-macro-helpers"]

[dependencies]
syn = "3.0.6"
quote = "1.0.47"
darling = "0.24.1"

[lib]
proc-macro = true
